name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./build-macos.sh
      - uses: softprops/action-gh-release@v1
        with:
          files: wbfs_file-MacOS-Universal2
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: ./build-linux.sh
      - uses: softprops/action-gh-release@v1
        with:
          files: wbfs_file-Linux-x86_64
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./build-windows.bat
      - uses: softprops/action-gh-release@v1
        with:
          files: wbfs_file-Windows-x86_64.exe
